Add Safari Doctors Youth Health Ambassadors app flavor.
medic/cht-android pull request #372
Opened 2024-09-09 05:41 UTC by benkags

2024-09-12 07:02 UTC, antonykhaemba commented
Hi @eljhkrr, I tagging you here since the apk is needed by tomorrow - sorry I am not able to assign this PR to you.

2024-09-12 12:02 UTC, eljhkrr commented
@benkags Confirm whether signing secrets have been setup within the repository

2024-09-12 12:03 UTC, eljhkrr commented
No worries @antonykhaemba, I've assigned myself

2024-09-12 14:50 UTC, benkags commented
@eljhkrr The secrets have not been set up. Let me now how I can share them securely

![{1C06F493-6333-44F9-9E25-95A9E9B4560E}](https://github.com/user-attachments/assets/700f328f-4088-440d-abef-a9491c328d2f)

2024-09-13 05:13 UTC, eljhkrr commented
Reassigned to Wambua as I'll be away today

2024-09-13 23:00 UTC, billwambua commented
@benkags can you [upload to 1password](https://support.1password.com/files/) and invite @eljhkrr and me.

2024-09-16 08:48 UTC, benkags commented
@billwambua I have shared the credentials via 1password. I have requested @eljhkrr 's email via email so that I can add him as well.

2024-09-16 10:26 UTC, billwambua commented
@benkags I tried opening the link you shared on email but it says "Not available"

![Screenshot from 2024-09-16 13-25-40](https://github.com/user-attachments/assets/288be611-1076-4e3b-9326-fb8ca7a5d47b)

2024-09-16 11:04 UTC, billwambua commented
@benkags for the 1Password invitation, you invited the wrong email. You are using the new shortened domain instead of the old medic domain which is what I created my 1Password account with.

This means I have to create a new account to join your invitation.

I have communicated with @antonykhaemba on the exact details you can use if you still don't understand what you need to do from the above. 

He will forward to you.

2024-09-16 15:56 UTC, benkags commented
Hi Bill, the BitWarden share expired.

@billwambua, I've shared with wa*@medicmobile.org address. Let me know if you can access now.

2024-09-16 16:08 UTC, billwambua commented
@benkags I'm in the workspace you have invited me to, but I can't see any Safari Doctors files.

2024-09-16 16:13 UTC, benkags commented
It was pending approval.

'View vault' so see the .env file uploaded.

![safari doctors 1password vault](https://github.com/user-attachments/assets/7fba3ef9-556d-4435-9a3a-43b15046b159)

2024-09-16 19:48 UTC, billwambua requested changes

2024-09-16 19:48 UTC, billwambua commented on .github/workflows/publish.yml
> +    - name: Bundle new_brand
Rename all instances of `new_brand` to `safaridoctors_kenya_yha` for consistency.

Make the naming consistent. You have `SAFARIDOCTORS_KE_YHA` in some places and `safaridoctors_kenya_yha` in others. Choose between `ke` and `kenya`.

2024-09-16 19:48 UTC, billwambua commented on .github/workflows/publish.yml
> +    - name: Assemble new_brand
Rename `new_brand` to `safaridoctors_kenya_yha` for consistency.

2024-09-16 19:48 UTC, billwambua commented on .github/workflows/publish.yml
> +      run: make org=new_brand keydec
Rename `new_brand` to `safaridoctors_kenya_yha` for consistency.

2024-09-16 19:49 UTC, billwambua commented
@benkags I don't have the appropriate permissions to add the secrets to Github Actions. 

@alexosugo can sort that.

2024-09-17 07:31 UTC, benkags commented
@billwambua, thanks. I've standardized the naming.

2024-09-17 12:52 UTC, billwambua approved these changes
LGTM.

Go ahead with setting the CI variables.

2024-09-17 14:50 UTC, jkuester approved these changes
LGTM!

2024-09-17 19:36 UTC, benkags commented
@jkuester I have shared the credentials in 1password to jk*@medic.org.

2024-09-17 19:45 UTC, jkuester commented
@benkags I received an email invite to make an account for your 1Password.  I did that (and my user is `jkuester`.)  But I cannot see any existing vault items.  Could you try sharing them with my `jkuester` account?

2024-09-17 20:12 UTC, benkags commented
Access was pending approval. Pleas try now. Check the vault items ford the .env file.

2024-09-17 20:50 UTC, mrjones-plip commented
I've added these secrets:
* `ANDROID_KEYSTORE_PASSWORD_SAFARIDOCTORS_KENYA_YHA`
* `ANDROID_KEY_PASSWORD_SAFARIDOCTORS_KENYA_YHA`
* `ANDROID_SECRETS_IV_SAFARIDOCTORS_KENYA_YHA`
* `ANDROID_SECRETS_KEY_SAFARIDOCTORS_KENYA_YHA`

![image](https://github.com/user-attachments/assets/1277173d-5b94-4113-b890-12d3ce804073)

2024-09-18 01:28 UTC, merged

2024-09-18 01:56 UTC, jkuester commented
Okay, I merged this to `master` and pushed a tag.  The release artifacts (`.apk` and `aab`) are available [here](https://github.com/medic/cht-android/releases/tag/untagged-b1d7f6de78d292712e37)  (look for the files `cht-android-v1.4.0-safaridoctors_kenya_yha-publish.1-safaridoctors_kenya_yha-*`).

2024-09-18 05:40 UTC, benkags commented
I don't have access to [this link](https://github.com/medic/cht-android/releases/tag/untagged-b1d7f6de78d292712e37). Are there additional privileges required. Is there another way to access the APKs before a [release tag](https://github.com/medic/cht-android/releases) is created?